Document: cw1
Title: Debian cw1 Manual
Author: Nishikant Taksande
Abstract: This manual describes what cw1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cw1/cw1.sgml.gz

Format: postscript
Files: /usr/share/doc/cw1/cw1.ps.gz

Format: text
Files: /usr/share/doc/cw1/cw1.text.gz

Format: HTML
Index: /usr/share/doc/cw1/html/index.html
Files: /usr/share/doc/cw1/html/*.html
